### ISSUE TITLE
Unit Testing as part of the example

### ISSUE THREAD

**Issue by musicm122** [SuavePirate/Xamarin.Flux#1]
Ello, I found the example clean and simple but was wondering what unit testing looks like.

**Comment by SuavePirate** [comment]
I talk a bit about Unit Test strategies with the Flux pattern in the GoneMobile podcast you can find here:
[Fluxing Up Your Xamarin Apps with Alex Dunn](http://gonemobile.io/blog/e0044.fluxing.up.your.xamarin.apps.with.alex.dunn/)

Basically, the best way to test your stuff is to abstract stuff into interfaces so you can test individual components, then using Inversion of Control to choose your actual implementation! So you can do this with your `Stores`, `Actions`, and `Views`. 

Another good way to test the flow is to have your stores set up with your tests, then make calls to your `Actions` just as your `ViewModels` would.

Here's a quick example:
```
[Test]
public void CreateItemTest()
{
    var store = new TodoStore();
    var actions = new TodoActions();
    actions.AddTodo("My test item");
    Assert.IsNotNull(store.Data.FirstOrDefault());
}
```

I'll add an example in the actual project at some point when I find time.
