### ISSUE TITLE
[Question] OnEmitted Callbacks on 2 ViewModels

### ISSUE THREAD

**Issue by ShahmanTeh** [SuavePirate/Xamarin.Flux#4]
Hi @SuavePirate , I have a question on the architecture setup for Flux.

I understand that the cycle for Xamarin.Flux is as follows.

`Action` > `Dispatcher` > `Store` > `ViewModel` > `View` > `ViewModel` > `Action` ...

so using event delegates, the ViewModel callbacks will mostly do DataBinding property change or UI-thread specific methods (such as show dialogs, navigation, etc ) or another `Action`

the problem i'm having is that what happens when i'm running another ViewModel that uses the same Flux Actions and Stores? because from what I read in this sample, it doesn't have event unsub.

Consider the scenario that I'm having problem right now.
`VM_A` class uses `Flux_Action_A` and `Flux_Store_A` . 

`VM_A` navigates to `VM_B` and then `VM_B` navigates to `VM_C`

`VM_C` uses `Flux_Action_A` , `Flux_Store_A` and `Flux_Action_B` , `Flux_Store_B` .

if `OnEmitted` is called, doesn't this mean that `VM_A` and `VM_C` will get the callback and will run the UI logic on each callback implementations?

I'm hoping to get some insights from you.

Regards,
Shahman Teh.

**Comment by SuavePirate** [comment]
Yes, if your ViewModels are still in memory and are still listening to events, they will receive their events and execute code. If you don't want that to happen, handle your event subscription with the lifecycle of the ViewModel. View not in scene? Don't listen to events.
